using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LyseisApi.Api.Admin.Entities.AdminEntities
{
    /// <summary>
    /// Companies table structure
    /// </summary>
    [Table("companies")]
    public class CompaniesEntity
    {
        /// <summary>
        /// Table primary key, autogenerated
        /// </summary>
        [Required]
        [StringLength(2)]
        [Key]
        [Column("cmp_id")]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public double Id { get; set; }
        
        /// <summary>
        /// Company tax information number
        /// </summary>
        [StringLength(12)]
        [Column("cmp_tax_information_number")]
        public int TaxInformationNumber { get; set; }

        /// <summary>
        /// Verification digit for company tax information number
        /// </summary>
        [StringLength(1)]
        [Column("cmp_digit")]
        public string NuidDigit { get; set; }

        /// <summary>
        /// Company name
        /// </summary>
        [StringLength(60)]
        [Column("cmp_company_name")]
        public string CompanyName { get; set; }

        /// <summary>
        /// Company address
        /// </summary>
        [StringLength(100)]
        [Column("cmp_address")]
        public string Address { get; set; }

        /// <summary>
        /// Company phone number
        /// </summary>
        [StringLength(30)]
        [Column("cmp_phone_number")]
        public string PhoneNumber { get; set; }

        /// <summary>
        /// Company mobile numer
        /// </summary>
        [StringLength(30)]
        [Column("cmp_mobile_number")]
        public string MobileNumber { get; set; }

        /// <summary>
        /// Company email
        /// </summary>
        [StringLength(50)]
        [Column("cmp_email")]
        public string Email { get; set; }

        /// <summary>
        /// Company web site
        /// </summary>
        [StringLength(100)]
        [Column("cmp_web_site")]
        public string WebSite { get; set; }
        
        /// <summary>
        /// Company logo url, hosted in public url no local path
        /// </summary>
        [StringLength(1000)]
        [Column("cmp_logo_url")]
        public string LogoUrl { get; set; }

        /// <summary>
        /// City name
        /// </summary>
        [StringLength(30)]
        [Column("cmp_city_name")]
        public string Ciudad { get; set; }

        /// <summary>
        /// Date of save the compay info
        /// </summary>
        [Column("created_at")]
        public DateTime CreatedAt { get; set; }

    }
}